apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeassignment-api
  labels:
    app: kubeassignment-api
env:
  - name: LOKI_URL
    value: "http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeassignment-api
  template:
    metadata:
      labels:
        app: kubeassignment-api
    spec:
      containers:
        - name: kubeassignment-api
          image: naveennk15/kubeassignment-api:bd70d0d
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 260m
              memory: 256Mi
